theme: jekyll-theme-dinky
title: "Colombian macro-vulnerabilities"
descrition: "We are a project that seeks to analyze to analyze through a Stock-Flow consistent model the vulnerabilities of Colombian economy in a low-carbon transition. Institutions: French Agency for Development, Ministry of Finance and Public Credit (Colombia), National Planning Department (Colombia) and National University of Colombia."
